# Generated by Django 4.2.13 on 2024-05-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='card',
            field=models.ImageField(blank=True, null=True, upload_to='images/cards/'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/raw_images/'),
        ),
    ]
