# Generated by Django 4.2.13 on 2024-05-26 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userdetails_card_alter_userdetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='expedition_date',
            field=models.CharField(default=datetime.datetime(2024, 5, 26, 2, 52, 27, 505027, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='expiration_date',
            field=models.CharField(default=datetime.datetime(2024, 5, 26, 2, 52, 35, 780636, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='graduated_in',
            field=models.CharField(default=datetime.datetime(2024, 5, 26, 2, 52, 42, 730916, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
